name: user_support_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  http: ^0.13.3
  shimmer: ^3.0.0
  d2_touch: 1.1.6
  dio: ^5.4.3+1
  draggable_scrollbar: ^0.1.0
  freezed_annotation: ^2.4.1
  intl: ^0.18.1
  provider: ^6.0.3
  reflectable: ^4.0.6
  flutter_easyloading: ^3.0.5
  # package_info_plus: ^1.4.2
  lottie: ^3.0.0
  internet_connection_checker_plus: ^1.0.1
  get: ^4.6.5
  json_annotation: ^4.8.1
  flutter_slidable: ^3.1.0
  go_router: ^14.2.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^2.3.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.14.1
  # freezed: ^0.15.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/lottie.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/dhis2logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  web:
    generate: true
    image_path: "assets/images/user_support.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"

  windows:
    generate: true
    image_path: "assets/images/user_support.png"
    icon_size: 256  # Larger size recommended for better scaling, max: 256

  macos:
    generate: true
    image_path: "assets/images/user_support.png"
